server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  rabbitmq:
    host: 172.17.250.200
    port: 5672
    username: admin
    password: admin123
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

foo: 卧槽有煞笔
