server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
        
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

foo: jkahdsfjkhsjkfdhasjkhd
